name: Publish Documentation

on:
  push:
    branches: 
      - main
      - '*'
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install dependencies 🔧
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv python install 3.11
          uv venv --python 3.11
          source .venv/bin/activate
          uv pip install -e .[docs]

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Sphinx build
        run: |
          uv run sphinx-build docs docs/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_ACTION_PAT }}
          publish_dir: docs/_build/
          force_orphan: true